# Generated by Django 5.1.2 on 2024-11-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronofy', '0002_calendlyuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlyuser',
            name='accessToken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calendlyuser',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
