# Generated by Django 5.1.2 on 2024-11-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronofy', '0003_alter_calendlyuser_accesstoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlyuser',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
