# Generated by Django 5.1.2 on 2024-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronofy', '0004_calendlyuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlyuser',
            name='scheduling_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
