# Generated by Django 5.1.2 on 2024-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronofy', '0005_calendlyuser_scheduling_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlyuser',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
